#
# VM for Mongodb server
#
# Copyright: (C) 2016-17 KINOSHITA minoru
# License: The MIT License (MIT)
#

require 'json'

#
# Read common configuration
#
ast_mongo_config = open("../config.json") do |io|
  JSON.load(io)
end

Vagrant.configure(2) do |config|
  #
  # Versions to install
  #
  mongodb = ast_mongo_config['mongodb']

  #
  # Hostname of VM
  #
  hostname = Dir.pwd.split('/').last

  #
  # Configuration of VM
  #
  config.vm.box = "parallels/ubuntu-16.04"
  config.vm.hostname = hostname
  config.vm.provider "parallels" do |prl|
    prl.memory = 1024
    prl.cpus = 1
  end

  #
  # Provision MongoDB server
  #
  config.vm.provision 'Wait for unattended-upgrades', type: 'shell', path: './wait_unattended_upgrades.sh', args: %w( dpkg apt unattended-upgrade )
  config.vm.provision "shell" do |s|
    s.inline = "sudo -u vagrant sh /vagrant/provision.sh $@"
    s.args   = [mongodb]
  end
end
