#
# VM for building Asterisk with Mongodb
#
# Copyright: (C) 2016 KINOSHITA minoru
# License: The MIT License (MIT)
#

Vagrant.configure(2) do |config|
  #
  # Versions to build
  #
  mongodb = '3.2'
  mongo_c_driver = '1.3.3'
  pjsip = '2.4.5'
  asterisk = '13.7.2'

  #
  # Hostname of VM
  #
  hostname = Dir.pwd.split('/').last

  #
  # Configuration of VM
  #
  config.vm.box = "parallels/ubuntu-14.04"
  config.vm.hostname = hostname
  config.vm.network "public_network"
  config.vm.provider "parallels" do |prl|
    prl.memory = 1024
    prl.cpus = 1
  end

  #
  # Provision Asterisk with the essential environments
  #
  config.vm.provision "shell" do |s|
    s.inline = "sudo -u vagrant sh /vagrant/provision.sh $@"
    s.args   = [mongodb, mongo_c_driver, pjsip, asterisk]
  end
end
