test:
	@./node_modules/.bin/mocha -t 10000 ./res_config_mongodb-test.js
	@./node_modules/.bin/mocha -t 10000 ./cdr_mongodb-test.js
	@./node_modules/.bin/mocha -t 10000 ./cel_mongodb-test.js

.PHONY: test
